#设置datasource
spring:
  datasource:
    url: jdbc:mysql://59.110.238.102:3306/hospital?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.tledu.cn.springbootdemo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl